### ISSUE TITLE
Shortcut items with no icon URL are ignored

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChromeLabs/bubblewrap#116]
Repro: `llama-pack init --manifest https://shortcut-bugs.web.app/manifest.json`.

Shortcut items with no icon URL are just ignored. `llama-pack` should provide some default icon in this case instead of ignoring them.

**Comment by andreban** [comment]
Looking at [this section](https://github.com/GoogleChromeLabs/llama-pack/blob/master/packages/core/template_project/app/build.gradle#L127-L132) of the template project, it seems this is by design. 

The icon is somewhat required on Android, as if the developer doesn't set it in `shortcuts.xml` Android will generate a default icon, an Android head, that is not meaningful to the action.

It doesn't sound to me that llama-pack would be better to provide a default icon that would be able to convey any better meaning to the actions. 

I do think we should alert developers of missing data in the shortcuts, so they know it's not being included and know how to fix it. 

@rayankans will know more about the current design.

**Comment by FluorescentHallucinogen** [comment]
> if the developer doesn't set it in shortcuts.xml Android will generate a default icon, an Android head

Just checked, can't confirm the case of item with no icon, the situation with WebAPK is very sad. I've opened https://crbug.com/1057380.

**Comment by rayankans** [comment]
Hi, I explained on the bug how the case with WebAPKs is related to caching and the fact that this hasn't been enabled on all channels.

As for llama-pack, as @andreban mentioned, this was a design decision. I could be convinced otherwise. Maybe a warning that it's being skipped is best for now? I believe that we we show developers a summary of the shortcuts included though when they are generating the TWA.

**Comment by andreban** [comment]
+1 to a warning of with what is being skipped and a summary of the shortcuts being included.

**Comment by FluorescentHallucinogen** [comment]
The web app manifest spec doesn't require icon for shortcut items, it's optional (see https://w3c.github.io/manifest/#example-11).

If the developer declared 5 shortcut items (and 2 of them have no icons) in the web app manifest for PWA, then he expects to see these 5 shortcut items for TWA (and 2 of them should have default icon — android heads).

I.e. we should skip items only if

* the property is required by spec (e.g. `"url"` or `"name"`), but for some reason is missing

or

* the property is present, but invalid

Since #103 is not fixed yet, if `"icons"`/`"src"` is SVG file, it breaks the build. As an idea, we could temporarily skip shortcut items like this until SVG will be supported.

BTW, is the number of shortcut items limited? What if the developer declared e.g. 100 items?

**Comment by andreban** [comment]
The manifest spec doesn't require it, but an Icon is required on Android. When an icon is not included in shortcuts.xml, a default icon is included, but results in a bad user experience. We want to ensure applications using Trusted Web Activity are high quality Android Apps. Therefore, it makes sense being more strict than the manifest spec in this case.

**Comment by FluorescentHallucinogen** [comment]
I believe we should align with WebAPK behavior.

@rayankans What if the icon for shortcut item is not provided in the manifest in case of WebAPK? Will it be android head icon or something else default icon? (Which exactly?) Or will this shortcut item be ignored?

And what if the icon has unsupported format (e.g. SVG)? Will this shortcut item be ignored or has default icon?

**Comment by rayankans** [comment]
@FluorescentHallucinogen WebAPKs don't ignore any shortcuts. They currently use a fully transparent icon if nothing was provided.

I don't think llama-pack should match behaviour with WebAPKs. It already gives the option to modify manifest values, or provide a custom manifest, so it makes sense to have its own quality enforcements.

I think a warning should suffice. @andreban any thoughts on the matter?

**Comment by andreban** [comment]
+1 to the warning.

**Comment by FluorescentHallucinogen** [comment]
@rayankans 
> WebAPKs don't ignore any shortcuts. They currently use a fully transparent icon if nothing was provided.

For me WebAPK always shows transparent icon even if icon is provided and has supported format. PTAL at https://crbug.com/1057380. You closed this issue with "WontFix" status, but it's not fixed! :-/

![shortcut-icons-bug](https://user-images.githubusercontent.com/7892779/76645763-abb62080-656a-11ea-9f7d-174fff2e6541.png)
