### ISSUE TITLE
bubblewrap 1.3 hangs on iconResponse.buffer()

### ISSUE THREAD

**Issue by JudahGabriel** [GoogleChromeLabs/bubblewrap#192]
I updated to bubblewrap/core 1.3.0, and now I'm seeing a hang that happens 90% of the time.

I added some console logs to help narrow down the issue. Here's what I see:

> twa-generator 	 C:\Users\judah\AppData\Local\Temp\pwabuilder-cloudapk-16772EXlDRT8RQ1lc\app\src\main\AndroidManifest.xml
> Log.js:116
> generating icons------------------------
> TwaGenerator.js:365
> fetching icon https://sadchonks.com/kitteh-512.png
> TwaGenerator.js:287
> successfully fetched icon https://sadchonks.com/kitteh-512.png with status code 200
> TwaGenerator.js:294
> about to grab buffer for icon https://sadchonks.com/kitteh-512.png

It hangs after "about to grab the buffer". In particular, that's [this line in TwaGenerator](https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/core/src/lib/TwaGenerator.ts#L211).

In short, it means fetching the image succeeds with a 200 result, but then accessing .buffer() hangs and never resolves. As a test, I did a .buffer().then(...).catch(...) to see it ever succeeded or failed. It did not, neither the `then` nor the `catch` is ever hit.

**Any idea why .buffer() might be hanging here?**

**Comment by andreban** [comment]
What seems to be freezing is a call to `node-fetch`. In practice, the initial `200` result is just the response header. The body of the content is pulled from the network when `response.buffer()` is invoked. My guess would be that there's a network issue where the download is not finishing. Since we don't set a timeout, it hangs forever.

I'm not sure this is due to an update in Bubblewrap. The last update to node-fetch was on `1.2.0`, so I'd expect things to fail there too. 

A couple of alternatives:
-  set a timeout when invoking `fetch` (`const response = await fetch(iconUrl, {timeout: 500});`) This can be long (or infinite / `0`) when running from the CLI, but should have a reasonable value when running from CloudAPK.
- Same thing, but using AbortSignal: https://github.com/node-fetch/node-fetch#request-cancellation-with-abortsignal.

**Comment by JudahGabriel** [comment]
Thanks. I suspect this is a Windows-specific or machine-specific issue. And kind of a distraction! The real issue I'm trying to debug is, when I send in shortcuts, I'm getting this error from Bubblewrap:

> TypeError: Only absolute URLs are supported

I don't get any more details about where that's coming from. The manifest I'm sending in:

```json
{ 
   "appVersion": "1.0.0",
   "backgroundColor": "#3f51b5",
   "enableNotifications": false,
   "host": "sadchonks.com",
   "iconUrl": "https://sadchonks.com/kitteh-512.png",
   "maskableIconUrl": null,
   "name": "Chonks",
   "navigationColor": "#3f51b5",
   "packageId": "com.chonks.twa",
   "shortcuts": [
      {
         "chosenIconUrl": "/favicon.png",
         "name": "New Chonks",
         "shortName": "New",
         "url": "/?shortcut"
      }
   ],
   "signingInfo": {
      "fullName": "Judah Himango", 
      "organization": "Test", 
      "organizationalUnit": "Engineering Department"
    },
   "signingKey": {
      "path": "C:/Users/judah/AppData/Local/Temp/pwabuilder-cloudapk-12444FHeQAeM6C42L/my-signing-key.keystore", 
      "alias": "my-key-alias"
   },
   "splashScreenFadeOutDuration": 300,
   "startUrl": "/saved",
   "themeColor": "#3f51b5",
   "useBrowserOnChromeOS": true
}
```

Any ideas?

**Comment by andreban** [comment]
The reason is that `chosenIconUrl` must be a complete URL, including the origin. In this case, `https://sadchonks.com/favicon.png`.

**Comment by andreban** [comment]
Here's how we extract the shortcuts from a Web Manifest in TwaManifest.ts: https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/core/src/lib/TwaManifest.ts#L207-L234

**Comment by JudahGabriel** [comment]
Since the hang is probably an environment issue, I'll close this for now.

Thanks for the tip about absolute URL for shortcuts. Since we're not calling `fromWebManifestJson`, we don't hit that code, so we must construct the `ShortcutInfo` objects ourselves. No problem, we'll pass in the full URL.
