### ISSUE TITLE
Update should preserve user configuration

### ISSUE THREAD

**Issue by nitzanashi** [GoogleChromeLabs/bubblewrap#216]
**Is your feature request related to a problem? Please describe.**
If I want to use ./gradlew to create a release I need to add release otpions the `build.gradle` file, but when I run `bubblewrap update` `build.gradle` will rewrite itself and my changes will be removed, although the changes I want to be affected are the one related to the manifest.

**Describe the solution you'd like**
`update` command will update only manifest related areas in the `build.gradle`

**Additional context**
I'm trying to create a github action to deliver a TWA with different manifests, therefore I need to use update quite often.

**Comment by andreban** [comment]
The way templating works is that Bubblewrap has a template `build.gradle` and applies changes to it. What are the changes you need on `build.gradle`? My guess is that it might be better to add those as part of the configuration, or allowing to provide a custom `build.gradle` template. Parsing the modified Gradle file in order to preserve manual changes is a much more complex problem and might be overkill.

**Comment by nitzanashi** [comment]
@andreban Thanks a lot for the fast responding, really appreciate that.

currently I'm not able to run `bubblewrap build` on my CI so I'm using `./gradlew` directly, but in menage to get a signed apk, I need to provide `signingConfigs` to the `buildTypes.release`.

your suggestions indeed make more sense to me as well

**Comment by andreban** [comment]
Would #172 help with `build` working on the CI?

**Comment by nitzanashi** [comment]
actually I managed to solve my issue, can run build on CI now.
