### ISSUE TITLE
Custom scheme: How to register a custom scheme, Also How does the enableNotifications options work

### ISSUE THREAD

**Issue by teclone** [GoogleChromeLabs/bubblewrap#224]
Please my apologises if I am asking the wrong question, or asking the question at the wrong place. I also want to express my gratitude for this project. I was able to launch the version 1 of our mobile app for [clacified intl](https://clacified.com/en).

I want to be able to register a custom and unique scheme that will not be handled by any other app in the android device. I was looking at the generated apk file and I see that there is only one intent scheme, which is https. I would want to register a custom and unique scheme name for my app. I still expect this scheme to be handled by the underlying android codes.

I am also confused about how the enable notifications option work. I handle push notifications using a service worker. But despite installing the app, my application still needs to request for notification permission. By setting the option to true, does it mean the app will have instant notification permission on install, also will it affect my current service worker implementation? This will be amazing if true.

**The solution I would like**
I want to have the ability to force users to read in-app, or to open in-app. Implementing this feature in the browser requires that I change the location to something like `android-app://scheme/path`. If the user happens to have my app installed, it works. The app gets opened.

But when the user does not have the app installed, chrome takes up the intent and opens the webpage, this is because most browsers have https/http registered in their schemes.

If I have a unique scheme registered, then nothing will happen, and I can set a timeout of like 250ms, which I can then redirect the user to playstore to download my app.

```
window.location.replace(`android-app://my-custom-scheme/path`);
setTimeout(() => {
   //redirect user to playstore to download the app
}, 250);
```

**Comment by andreban** [comment]
You can define a custom schema for your  app by defining a custom intent-filter. There are more details on the android docs here: https://developer.android.com/guide/topics/manifest/intent-filter-element. This is largely outside the scope of Bubblewrap.

Regarding notification delegation, yes, this will delegate the notification permission to the Android app, which gets permissions enabled by default.

Regarding the last point, It seems what you are looking for is to launch the app if it is installed, otherwise open the Play Store. The API to achieve this is https://web.dev/get-installed-related-apps/ -  It allows querying if the app is installed. With that information you can decide on launching the app or opening the store.
