### ISSUE TITLE
TWA Google Play in-app Billing

### ISSUE THREAD

**Issue by githubbla** [GoogleChromeLabs/bubblewrap#234]
How to make Google Play in-app Billing from TWA?
with different payment processor from  Google Play in-app Billing impossible to upload to Google Play.

**Comment by andreban** [comment]
Support for Play Billing is in development both in Chrome and in the support library. Keep an eye on https://github.com/GoogleChrome/android-browser-helper/. Once support is implemented in both, we'll bring it to Bubblewrap.

**Comment by FluorescentHallucinogen** [comment]
@andreban @PEConn Could you please then explain what https://github.com/GoogleChrome/android-browser-helper/tree/master/playbilling directory and https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/payment-provider demo are? :-/ Do they work now without https://chromestatus.com/feature/5339955595313152 implemented?

**Comment by nitzanashi** [comment]
I guess it might be a noob question but if we use the [Google Pay API](https://developers.google.com/pay/api) would it be fine for the Google Play store or is it not a valid solution?

**Comment by PEConn** [comment]
The `playbilling` module and demo are currently a work in progress - they are the TWA side counterparts to the Digital Goods API. Once the Digital Goods API is released and playbilling is finished, user's will be able to use the Digital Goods API to communicate with Play Billing through their TWA.

So the problem is that if you distribute an app through the Play Store (which applies to TWAs) and you take payments for Digital Goods, you must use the Play Billing Android API to accept those payments. The Digital Goods API and `playbilling` module aim to make that work so you can just use the Digital Goods JavaScript API from within your website. I don't think the Google Pay API is appropriate as it doesn't seem like that knows anything about Android Play Billing (I don't know that 100% though).
