### ISSUE TITLE
Clarify the keystore usage

### ISSUE THREAD

**Issue by dandv** [GoogleChromeLabs/bubblewrap#254]
**Is your feature request related to a problem? Please describe.**
For web developers unfamiliar with android, the keystore may be confusing.

**Describe the solution you'd like**
While running `bubblewrap build`,
> ? Password for the Key Store

can be interpreted as both "What is the password for the keystore", and "Set a password for the keystore"

Same for

> ? Password for the Key:

The previous prompts are ambiguous as well. I ended up creating a directory ("store"):

> ? Key store location: ./android.keystore
> ? Key name: ./android.keystore

Then I got this error,
> Failed to load signer "signer #1"
>java.io.FileNotFoundException: ./android.keystore (Is a directory)

**Describe alternatives you've considered**
PWABuilder?

**Additional context**
Ideally, a web dev who's never touched Android development, should be able to build a TWA from their PWA.

**Comment by andreban** [comment]
Regarding the key store location and name prompts, we recently introduced an explanation right before the questions. There's a bug where the default alias should be `android` instead of `./android.keystore`. Builds still work though.

<img width="949" alt="Screen Shot 2020-07-21 at 07 53 02" src="https://user-images.githubusercontent.com/1733592/88022551-6365cb00-cb27-11ea-8b08-bfc2d8b39197.png">

We could add more context when asking for the passwords during the build step, similar to the above.

**Comment by andreban** [comment]
#255 will fix using the correct alias by default.
