### ISSUE TITLE
Allow assetStatements to be specified in twa-manifest

### ISSUE THREAD

**Issue by kidandcat** [GoogleChromeLabs/bubblewrap#268]
**Is your feature request related to a problem? Please describe.**
We want an app to open external URLs as they were part of the app itself

**Describe the solution you'd like**
We would like to be able to add (resValue "string", "assetStatements") directly in the twa-manifest

**Describe alternatives you've considered**
We are extending resValue "string", "assetStatements" in build.gradle, but it gets overwrited when executing "bubblewrap update"

**Comment by andreban** [comment]
> We want an app to open external URLs as they were part of the app itself

I'm guessing those are origin you have control of and can deploy an `assetlinks.json` file.

> We would like to be able to add (resValue "string", "assetStatements") directly in the twa-manifest

Looks like you are trying to build a [multi-origin Trusted Web Activity](https://developers.google.com/web/android/trusted-web-activity/multi-origin). It's not currently supported in Bubblewrap. Instead of defining asset_statements inside the twa-manifest, it may better to just ask for additional origins, and we can ensure the statement is well-formed.

**Comment by kidandcat** [comment]
Yeah, that's exactly what I'm doing, so the only thing needed to support multi-origin TWAs is to add those origins to the asset statements, so it should be easy to implement. I agree about extending origin to be an array for example.

Will you work on it? or should I open a PR?

**Comment by andreban** [comment]
It looks like we'd need an optional `additionalOrigins`, as an array type in `twa-manifest.json`, as we need to know what the main one is. 

I'm not planning on implementing this at the moment, so a PR would be greatly appreciated.
