### ISSUE TITLE
Allow option to choose which browser should be used to open the app

### ISSUE THREAD

**Issue by PrimarchAlpharius** [GoogleChromeLabs/bubblewrap#274]
**Is your feature request related to a problem? Please describe.**
Most browsers currently don't support TWA, and fallback to a custom tab (with the navigation bar) or webview (which can cause other issues) is suboptimal. Currently it is very hard for a non-Android developer to force loading of the TWA app in Chrome instead of the default browser.

**Describe the solution you'd like**
Allow for an option to specify which browser should be used first to open the app, overriding the default browser. If the selected browser is not installed on the system, fall back to the initial behaviour.

**Describe alternatives you've considered**
From what I've seen it's possible to do this by modifying the build files https://stackoverflow.com/questions/55531080/pwa-with-twa-how-to-force-chrome-instead-of-default-browser, but how exactly is not very clear to non-Android devs.

**Comment by PEConn** [comment]
Hey,

The logic we use for determining which browser to use is [here](https://github.com/GoogleChrome/android-browser-helper/blob/cdf4934f8be375b813fca2c8223281396b03e076/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/TwaProviderPicker.java), it's essentially:
1. Look for browsers that support TWAs, if you find one, pick it.
2. Otherwise, look for browser that support Custom Tabs, if you find one, pick it.
3. Otherwise launch to the default browser.

From your question, I'm assuming you've seen bugs where a TWA has been opened in another browser (eg, with Custom Tabs UI). This could mean one of three things:

* The user didn't have a supporting version of Chrome on their device (otherwise it would have been picked).
* The user's default browser claims to support TWAs, but doesn't.
* There is a bug in our browser picking logic.

Do you know anything that could help narrow this down?

**Comment by PrimarchAlpharius** [comment]
Hey,

the default browser in question was Brave, but upon further investigation, the cause of the issue was a misconfiguration on my side.
It's working fine even with Brave, actually.

Sorry about the false alarm, and thumbs up for the great work you're doing here! ;)

Closing the thread.

**Comment by andreban** [comment]
Thanks for follow-up, @PrimarchAlpharius - do you have more details on what the misconfiguration was? Anything we could do to help other devs avoid that?
