### ISSUE TITLE
Add a version code prompt

### ISSUE THREAD

**Issue by nohe427** [GoogleChromeLabs/bubblewrap#322]
**Is your feature request related to a problem? Please describe.**
This feature request is related to the fact that if I have an existing Android application, I need a version code that has not been used before (and preferably) a higher integer than the current version code.

**Describe the solution you'd like**
A prompt for me to select the version code I would like on init.

**Describe alternatives you've considered**
A flag instead of a prompt.

**Additional context**
none.

**Comment by magbicaleman** [comment]
I would be under the impression that `twa-manifest.json` is where you make this update, but it does change anything, and keeps building version name `1` and version code `1` no matter what I change in the `twa-manifest.json`.

**Comment by andreban** [comment]
@magbicaleman after making changes to `twa-manifest.json` you'll need to run `bubblewrap update`. This will regenerate the source for the Android app. `appVersionName` and `appVersionCode` will be bumped automatically when `update` is invoked.

This issue is about setting a starting `appVersionCode` when generating the app for the first time. The use-case would be a developer replacing an existing app, which will already have a higher version, and initialising the app with that.
