### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by mcmultimedia** [GoogleChromeLabs/bubblewrap#334]
Can APKs and AABs created run on Android TV. A friend asked me because he owns Android TV and therefore wanted the right answer for him.

**Comment by andreban** [comment]
Unfortunately, Android TV doesn't devices usually don't have a browser, so Trusted Web Activity won't work there. A common solution is using a WebView to wrap the web experience.

Closing the issue, as this is currently outside the scope of Bubblewrap (due to the lack of a browser in Android TV devices).
