### ISSUE TITLE
Enable the android-browser-helper/playbilling extension

### ISSUE THREAD

**Issue by mcmultimedia** [GoogleChromeLabs/bubblewrap#339]
is it  possible for TWAs to handle in APP Purchases? If yes, how can it be done?

**Comment by PEConn** [comment]
At the moment, not easily.

If you created a TWA manually (creating an Android app based on android-browser-helper) you can create native Android Activities that interact with Play Billing and you can link to them from your web content.

We are however working on adding Play Billing support, so that if you use the Web Payments API from within a TWA, it will use Play Billing. This hopefully should be completed before the end of the year.

**Comment by andreban** [comment]
Tracking this via #376
