### ISSUE TITLE
Bubblewrap error on first launch on Linux 9: The given androidSdk isn't correct.

### ISSUE THREAD

**Issue by AlexDev404** [GoogleChromeLabs/bubblewrap#397]
I have bubblewrap/cli latest installed on my Linux machine. I have just installed Bubblewrap on it and now it's asking me to give the location of the JDK and Android SDK. Alright then, I put in the location of both of them. That worked, but only for the JDK. When I tried putting in the location for the Android SDK it did not work, instead it spitted out the error that is entitled:

> `The given androidSdk isn't correct.`

What does this error mean? I distinctly remember downloading the SDK that you had linked in the `*README.MD*` file and now it's not working. I even tried redownloading the file over five consecutive  times. Please reply.

**To Reproduce**
1. Install bubblewrap using `npm install -g @bubblewrap/cli`
1. Download the SDK using the link in the ReadMe.md file
2. Type in the commandline: bubblewrap init -manifest=_pwa_goes_here_
3. Give the location of the JDK 8 installation you have
1. Give the link of the Android SDK

**Expected behavior**
Bubblewrap should now output the error:
> `>> The given androidSdk isn't correct.`

**Screenshots**
![Screenshot (36)](https://user-images.githubusercontent.com/34188635/99127439-f1c9f500-25cd-11eb-95ab-bb285816cf8e.png)

**Desktop (please complete the following information):**
 - OS: Debian 9
 - Browser: Google Chrome
 - Version 86

**Smartphone (please complete the following information):**
N/A

**Comment by andreban** [comment]
Can you please clarify:
- What's the path to the Android SDK being used?
- Does this folder contain a `tools` folder inside it?

The next version of Bubblewrap will give the developer the choice of download the tool automatically, and avoid issues with paths.

**Comment by AlexDev404** [comment]
@andreban Hello and sorry for the unprofessional feedback submitted. I just got tired of trying over and over again to get the thing working. To clarify your question:

- The Android SDK is located at exactly `/home/codespace/workspace/TurboWarp-Desktop/sdks/android-sdk`
- And no, there is no `tools` folder located in the directory

**Comment by andreban** [comment]
The problem is that the lates released of the Android command line tools has changed the directory structure. As an example. the `sdkmanager` script used to be at:

 `$SDK_ROOT/tools/bin/sdkmanager` and is now located at `$SDK_ROOT/bin/sdkmanager`.

Workarounds: 
1. Use Bubblewrap [`1.8.0-alpha.1`](https://www.npmjs.com/package/@bubblewrap/cli/v/1.8.0-alpha.1), which will download the right JDK and Android SDK:

```
npm i @bubblewrap/cli@1.8.0-alpha.1
```

2. Build the old folder structure manually:
   1. Create a `tools` folder inside the `android-sdk` folder.
   2. Move all the content from the `android-sdk` folder (excluding the newly created `tools`) into the `tools` folder.

I'll start work on a proper Bubblewrap update that handles the directory structure change.
