### ISSUE TITLE
Does bubblewrap APK need a specific dependency?

### ISSUE THREAD

**Issue by ouweiya** [GoogleChromeLabs/bubblewrap#460]
Can the APK built by bubblewrap run on any Android phone? Do you need specific dependencies? For example: need to install Chrome browser, need Google service framework? What are the limitations compared with native APP?

**Comment by PEConn** [comment]
If the user has a supporting browser (there's a [list here](https://github.com/GoogleChrome/android-browser-helper/blob/aa3a642284b3ba59cff2384cc9631fc70a6239f6/docs/trusted-web-activity-browser-support.md)), your app will launch as a TWA in that browser.

If not, it will launch in the [Custom Tabs UI](https://developer.chrome.com/docs/multidevice/android/customtabs/), if there is a browser on the device that supports that (most devices should have one).

Finally, if both of those fail, it will launch your website in a browser tab.

Your app will only require Google service framework if you want to use Play Billing.

**Comment by andreban** [comment]
As Peter mentioned,

- The application generated by Bubblewrap will work better on a [browser that supports Trusted Web Activity](https://github.com/GoogleChrome/android-browser-helper/blob/aa3a642284b3ba59cff2384cc9631fc70a6239f6/docs/trusted-web-activity-browser-support.md).
- However, it is possible to enable a WebView fallback, which will give users a fullscreen experience, but is limited because of the WebView limitations.
- Trusted Web Activities are a browser feature, built on top of core Android components (Activites, Intents, Services). Google services are not required.
- However, Google Services are required to enable the Google Play Billing integration.
