### ISSUE TITLE
Do I need to preserve the output of `bubblewrap build`?

### ISSUE THREAD

**Issue by hhimanshu** [GoogleChromeLabs/bubblewrap#566]
Hello

I am new to creating artifact for my PWA. I have correctly deployed [assetlinks.json](https://react-pwa-starter.vercel.app/.well-known/assetlinks.json) in my application root.

I am using the following version of `bubblewrap`
```sh
➜  pwa-app-store bubblewrap version
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
                                                           `--'
version 1.13.2
➜  pwa-app-store
```

I ran the following commands (in order) to generate `apk`, and `aab` files
```sh
bubblewrap init --manifest=https://react-pwa-starter.vercel.app/manifest.json
bubblewrap build
```
The following output was generated
```sh
➜  pwa-app-store ll
total 2680
-rw-r--r--  1 hhimanshu  staff   2.1K 19 Jul 10:02 android.keystore
drwxr-xr-x  5 hhimanshu  staff   160B 19 Jul 10:02 app
-rw-r--r--@ 1 hhimanshu  staff   369K 19 Jul 13:27 app-release-bundle.aab
-rw-r--r--@ 1 hhimanshu  staff   414K 19 Jul 13:26 app-release-signed.apk
-rw-r--r--  1 hhimanshu  staff   5.5K 19 Jul 13:26 app-release-signed.apk.idsig
-rw-r--r--@ 1 hhimanshu  staff   401K 19 Jul 13:26 app-release-unsigned-aligned.apk
-rw-r--r--  1 hhimanshu  staff   1.1K 19 Jul 13:26 build.gradle
drwxr-xr-x  3 hhimanshu  staff    96B 19 Jul 10:02 gradle
-rw-r--r--  1 hhimanshu  staff   751B 19 Jul 13:26 gradle.properties
-rwxr-xr-x  1 hhimanshu  staff   5.8K 19 Jul 13:26 gradlew
-rw-r--r--  1 hhimanshu  staff   2.9K 19 Jul 13:26 gradlew.bat
-rw-r--r--  1 hhimanshu  staff    40B 19 Jul 13:26 manifest-checksum.txt
-rw-r--r--  1 hhimanshu  staff    15B 19 Jul 13:26 settings.gradle
-rw-r--r--@ 1 hhimanshu  staff    37K 19 Jul 13:26 store_icon.png
-rw-r--r--  1 hhimanshu  staff   1.2K 19 Jul 13:26 twa-manifest.json
```

Now, the first time, I uploaded `apk` file in Play Store and waited for 2-3 days for app to approve. Then, when I tested it this morning, I saw address bar on my Android Chrome.

So, I removed all artifacts (include android.keystore) and recreated all artifacts locally, thinking I may have done something wrong, but now, when I upload I get another error

```
You uploaded an APK that is not signed with the upload certificate. You must use the same certificate. The upload certificate has fingerprint:
SHA1: FD:9D:45:6B:2D:FC:5A:AA:73:64:54:1D:C2:XXXXXXXXXXXXXXX
and the certificate used to sign the APK you uploaded has fingerprint:
SHA1: BD:43:ED:C8:B5:CD:D2:DE:64:DB:EB:55:00:XXXXXXXXXXXXXX
```
<img width="709" alt="Screen Shot 2021-07-19 at 1 37 01 PM" src="https://user-images.githubusercontent.com/6589036/126224063-102936cf-e8b6-4def-8850-6eaa6ddbd772.png">

Have I made mistake in the process? Did I had to source-control the artifacts produced by `bubblewrap build`? I am not able to make progress.

Please advise.
Thank you

**Comment by joycetoh8** [comment]
Hi Harit,

Thanks for reaching out! You're seeing that error message from the Play Console because you're using a different upload/signing key. As you said, you removed `android.keystore` which stores the information about your signing key. So when you tried to rebuild and recreate the artifacts locally, it created a brand new keystore and key for you which won't match the previous one you had. For security reasons, Google Play will require you to use the same key to sign apks/app bundles for the same listing. If you're not able to retrieve the previous `android.keystore`, you have a couple options:
- If you opted in to [Play App Signing](https://support.google.com/googleplay/android-developer/answer/9842756?hl=en#zippy=%2Cnew-apps), the good news is that you can go through the process to [create a new upload key and reset it](https://support.google.com/googleplay/android-developer/answer/9842756?visit_id=637623244562052340-1177343061&rd=1#reset). Note that this process may take a day or two.
- If you did not opt in to Play App Signing or you don't want to wait for the support team to reset your key, the only other option is to create a brand new listing. When you don't opt in to play app signing, this means you have sole access to the signing key and if you lose it, there's nothing the Play team can do to retrieve it. This could be okay if you were only creating a test listing and this isn't a production release listing you wanted to use.

For future reference, the response to issue #286 can help you understand what you should commit to version control (we're working on improving our documentation soon!) Specifically, Andre's response explains more about the keystore:

>How to handle the keystore file safely?

> I wouldn't add android.keystore to the version control, specially if that's something like GitHub. You probably want to store in a place where:
- The file is backed-up so an HD crash won't get you in a place where you can't update your app anymore.
There's strict access control where only people who need to sign the APK for production and upload to the store have access.
- I'd also opt-in into App Signing so Play can manage the key for you - when opting into Play Signing, the key generated by Bubblewrap becomes the "upload key" and the "signing key" is managed by Play. Otherwise, the key generated by Bubblewrap is the "signing key". With App Signing, you can change the "upload key" if you lose it or if it leaks. Without App Signing, it isn't possible to update it and losing means you can't update your app on the store anymore.

You noted that you were seeing the address bar which likely means you were seeing a Chrome Custom Tab. This is probably an issue with your digital asset links verification. I recommend checking [this video](https://www.youtube.com/watch?v=3bAQPnxLd4c) out for more info. Specifically, at around the 2:00 minute mark is how you can get the correct SHA256 fingerprint for your app from Google Play.

Hope this helps!

**Comment by hhimanshu** [comment]
Hello @joycetoh8,
Thank you so much for the wealth of information, this means a lot to me.
I read it multiple times to make sure I can understand my action items, given what my situation is. I divided this into 3 parts

`Re-create upload key` => `Re-generate bundle` => `Re-generate assetlinks.json`.

I will also try to preserve the artifacts as mentioned by @andreban in [this comment](https://github.com/GoogleChromeLabs/bubblewrap/issues/286#issuecomment-675479535).

As I make progress, I will report it here and to validate, and hopefully document for other folks who will cross this path.

Before I start on the first step, I want to acknowledge that I opted for App Signing as it was the recommended way.

As for creating the `apk` file, I have been following [Quick Start](https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/) guide, but, it doesn't mention anything related to creation of the upload key.
Additionally, I do see in my account that I have "Upload key certificate", and I am *assuming* that it is the upload key I need to use. Is that understanding correct? I also see "Download certificate" option here, is it something I can use to create the bundle again? 

Please let me know. Thanks again, @joycetoh8 for your help

**Comment by joycetoh8** [comment]
My pleasure, @hhimanshu. I know some of these steps can be confusing. I've been in your shoes myself, so I'm happy to help!

The three steps you've got there look good! Here are some additional details for each step:
1. Recreate upload key:
- You've actually already created a new upload key when you regenerated your artifacts again with Bubblewrap. You should see in your Bubblewrap project directory, the `android.keystore` file (this is the default name; it may be different if you changed the path during the `bubblewrap init` prompt during the "Signing key information (5/5)" portion.
- Next is to let the Google Play support team know about your new upload key. Fill out [this form](https://support.google.com/googleplay/android-developer/contact/key) like so
<img width="701" alt="reset-key" src="https://user-images.githubusercontent.com/5619655/126240316-5a7cee81-3d21-4f3f-90e9-dc095c876fd0.png"> 
- You can skip the step to generate a new key, since Bubblewrap already did that for you. You'll just need to do step "2. Export the certificate for that key to PEM format" where you can replace `keystore.jks` with the path to `android.keystore` or whatever you've named your file. This should generate the `upload_certificate.pem` file which you should attach as part of that form. 
- Wait for an email from the Play support team confirming that they've reset your key with the new upload key. May take a couple days.

2. Regenerate APK/Android App Bundle:
- Double-check the `twa-manifest.json` file. Make sure the `signingKey` field correctly points to the `android.keystore` file.
- Run `bubblewrap build`.
- Then upload your APK/AAB to the Play Console. Hopefully the new upload key works and you're not seeing the error you were seeing before.

3. Regenerate assetlinks.json
- In the Play Console, in the nav menu for your app listing, go to Release -> Setup -> App integrity. Copy the SHA256 fingerprint for the "App signing key certificate" (not Upload key certificate). This should go in your assetlinks.json

> Additionally, I do see in my account that I have "Upload key certificate", and I am assuming that it is the upload key I need to use. Is that understanding correct? I also see "Download certificate" option here, is it something I can use to create the bundle again?

Yes, so the "Upload key certificate" you see there is for the original key you had (before you deleted the file and regenerated the project). That's the upload key the Play Console expects you to use but you don't have it anymore. So step 1 above asks Play to reset that for you. "Download certificate" will download the public certificate for your key. It won't give you the actual key. You, as the developer, are the only one with access to your private upload key. Which is why it's important to not misplace it or leak it.

**Comment by hhimanshu** [comment]
Alright, so I have an update to report here.
I found out that my `assetlinks.json` file structure was incorrect. Once I [fixed it](https://github.com/hhimanshu/react-pwa-starter/pull/8/files), I was able to verify that using the [pull request deployment URL](https://github.com/hhimanshu/react-pwa-starter/pull/8#issuecomment-882935672)

Once I merged the PR, I un-installed and re-installed App from the Play Store. I have my app in [Open Testing](https://play.google.com/store/apps/details?id=app.vercel.react_pwa_starter.twa) right now.

Once installed, I opened and the app worked fine, **without** Chrome Custom Tab (CCT). This is great, something I was looking to achieve.

To summarize, the problem was the incorrect structure of `assetlinks.json` file.

But this opened another set of questions, which I am wondering about, and taking help from you experts (@joycetoh8, @andreban) makes lot more sense to me. My questions are outlined below

1. The `assetlinks.json` that I [create](https://github.com/hhimanshu/react-pwa-starter/blob/main/scripts/generateAssetLinks.ts#L8-L9) depends on values that I copy from Play Store App Signing. So, I have only 1 key [here](https://react-pwa-starter.vercel.app/.well-known/assetlinks.json). However, this does not work when I deploy from my machine because it seems it does not have the SHA-256 fingerprint from my local build. I found a separate fingerprint using [Peter Asset Link Tool](https://play.google.com/store/apps/details?id=dev.conn.assetlinkstool&hl=en_US&gl=US). So, is it required to have this key in `<APP_ROOT>/.well-known/assetlinks.json`? Can't it work based on the key that Google generated?
2. I did not had to use upload key during the entire process. Is it required? And in which step? The [Quick Start](https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/) guide doesn't talk about it.
3. If I only backup `twa-manifest.json` and `android.keystore` (this one not backed up in git), it should be enough to create another version of `apk`, `aab` files by calling `bubblewrap update` (as per @andreban's comment). Is that understanding correct?
4. Since I have a PWA and my only goal is to take the app to Play Store, so that it can be discovered and deployed, do I ever need to update the app once I deployed it once? Ideally, the `apk` is only the container, and I plan to update app using ServiceWorker updates?

I know I asked a lot of questions, but they are essential to getting to a complete understanding, so I sincerely request your help in getting these answers. As a THANK YOU note, I can commit, to write a documentation for this entire piece for other web developers.

Looking forward to learning from you folks! and THANK YOU once again!

**Comment by andreban** [comment]
> The assetlinks.json that I create depends on values that I copy from Play Store App Signing. So, I have only 1 key here. However, this does not work when I deploy from my machine because it seems it does not have the SHA-256 fingerprint from my local build. I found a separate fingerprint using Peter Asset Link Tool. So, is it required to have this key in <APP_ROOT>/.well-known/assetlinks.json? Can't it work based on the key that Google generated?

This happens because, when building locally, android.keystore is used to sign the APK that you upload to the device. When uploading to Play, App Signing will use a different key. The one used by App Signing is the one your users are going to use.

However, it's quite handy to be able to use both keys, so you can easily debug locally.  This section of the quick start guide shows how to enable both keys: https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/#adding-more-keys

> I did not had to use upload key during the entire process. Is it required? And in which step? The Quick Start guide doesn't talk about it.

You are not using it directly, but Bubblewrap is using it to sign the .aab file and the .apk file.

> If I only backup twa-manifest.json and android.keystore (this one not backed up in git), it should be enough to create another version of apk, aab files by calling bubblewrap update (as per @andreban's comment). Is that understanding correct?

That's right. Don't forget to safely store the passwords too (but not in the version control).

> Since I have a PWA and my only goal is to take the app to Play Store, so that it can be discovered and deployed, do I ever need to update the app once I deployed it once? Ideally, the apk is only the container, and I plan to update app using ServiceWorker updates?

Yes, you should update your app from time to time. There are mainly two reasons for this - if you update your Web Manifest - like changing the app name or icon - you'll probably want that change reflected in your app on Play. The other reason is that we frequently release updates to Bubblewrap, with new features, bugfixes, and general updates that you will want to apply to your app. Generally, I'd recommend updating it at least once every 6 months. 

Hope this helps,
Andre

**Comment by hhimanshu** [comment]
Hello @joycetoh8 and @andreban,
You folks have made me learn so much in last 1 day than I have tried with different links in past few days, so THANK YOU!

Based on discussion, it seems I need to do the following

## Re-create the app bundle. 
For this, I need to start fresh with bubblewrap. The re-generation process should be done in codebase itself with `.gitignore` to ignore all files except `twa-manifest.json`.

The other file generated by bubblewrap, called `android.keystore` is extremely important, but should not be checked into version control since it contains private keys. You can keep this safe somewhere else.

## Re-generate upload key and inform Google
Since the app is already published (in [Open testing](https://play.google.com/store/apps/details?id=app.vercel.react_pwa_starter.twa)), Google expect the same keys for newer versions as well. Since I have lost the original `android.keystore`, I need to generate new keys and tell Google to update new keys. The process is outlined in https://github.com/GoogleChromeLabs/bubblewrap/issues/566#issuecomment-882949928

There could be a wait 2-3 days once the request is submitted to Google.

## Create `assetlinks.json` to enable local debugging as well

The Digital Asset Link verification depends on set of keys generated using 2 ways

1. When you installed your app on your phone using a USB device, you use keys generated in file android.keystore generated by bubblewrap build. 
2. When you submit your app on Play Store, and you have signed in for App Signing, Google creates and manage the keys for you.

The `APP_ROOT/.well-known/assetlinks.json` must contain both the keys for successful digital links verification. If the verification fails, users/you will see Chrome Custom Tabs (with Address Bar)

Do you folks think I am still missing anything? I would love to get it reviewed from you both.

I will get started on the action items soon, and update my progress here.

Thank you very much once again, you folks rock 💪

**Comment by joycetoh8** [comment]
That all sounds great to me! I think you've got everything :)

**Comment by hhimanshu** [comment]
I have an update as per my action items
## Re-create the app bundle
The goal is to have `bubblewrap` dependencies in project itself that to install them globally on the machine. This way, it can work in CI process such as Github Actions
Then, the following commands helped me to generate new `android.keystore` for the project
```sh
npx bubblewrap init --manifest=https://react-pwa-starter.vercel.app/manifest.json --directory pwa
cd pwa && bubblewrap build
```
I am working on a PR that reflects this change. The code is available at https://github.com/hhimanshu/react-pwa-starter/pull/9/files
I have securely saved the following in password manager
- `android.keystore`
- Password for the keystore (asked during bubblewrap command)
- Password for the key (asked during bubblewrap command)

## Re-generate upload key and inform Google
I regenerated the `upload_certificate.pem` file using the following command
```sh
➜  pwa git:(hhimanshu/DEV-34-app-bundle) ✗ keytool -export -rfc -alias android -file upload_certificate.pem -keystore android.keystore
Enter keystore password:
Certificate stored in file <upload_certificate.pem>

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore android.keystore -destkeystore android.keystore -deststoretype pkcs12".
```
Please note that -
- `-alias <aliasName>`, where `aliasName` is the name you choose when using bubblewrap command
- `-keystore <keystore_filename>`, where `keystore_filename` is the name you choose when using bubblewrap command
-
Next, I used [this link](https://support.google.com/googleplay/android-developer/contact/key) from the Google account from which I have published my app. This has helped to fill out most details automatically for me.

I followed the steps outlined by @joycetoh8  in [her comment](https://github.com/GoogleChromeLabs/bubblewrap/issues/566#issuecomment-882949928)

Finally, I submitted the request to Google as of **Jul 20, 2021 at 4:00 PM PST**. I will update here when I hear back from the team.
<img width="897" alt="Screen Shot 2021-07-20 at 4 02 44 PM" src="https://user-images.githubusercontent.com/6589036/126406760-5e9b0338-8a48-4317-b166-2b5f260d23fd.png">

Thank you @joycetoh8  and @andreban. I have been able to follow 2 steps exactly as you folks have outlined. I will now work on next step and update here soon.

**Comment by hhimanshu** [comment]
I have another update to make, this time it is for final action item
## Create `assetlinks.json` to enable local debugging as well
Instead of using *Peter Asset Link Tool*, I used the following command to get the SHA-256 fingerprint from the `android.keystore`. The goal is to have app install on local machine without Custom Chrome Tab. I also want to integrate this as part of CI process, that's why I chose this path
```
➜  pwa git:(hhimanshu/DEV-34-app-bundle) ✗ keytool -list -v -keystore android.keystore
Enter keystore password:
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: android
Creation date: Jul. 20, 2021
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=Harit Himanshu, OU=Engineering, O=BonsaiiLabs, C=CA
Issuer: CN=Harit Himanshu, OU=Engineering, O=BonsaiiLabs, C=CA
Serial number: f842c25
Valid from: Tue Jul 20 13:29:57 PDT 2021 until: Wed Apr 22 13:29:57 PDT 2076
Certificate fingerprints:
	 SHA1: 00:0D:A1:40:52:D8:D9:F2:2C:C8:A6:47:18:XXXXXXXXXXXXXXXXX
	 SHA256: B9:C1:E6:D4:74:43:95:74:C3:34:98:D9:3B:7D:A4:A9:6B:XXXXXXXXXXXXXXXXXX
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: BD 4B BE 96 DC  99 6D 5C D2 01 9A E6 E9  .K.......m\.....
0010: 29 07 10 01                                        )...
]
]



*******************************************
*******************************************



Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore android.keystore -destkeystore android.keystore -deststoretype pkcs12".
```
I copied the value from 
```
SHA256: B9:C1:E6:D4:74:43:95:74:C3:34:98:D9:3B:7D:A4:A9:6B:XXXXXXXXXXXXXXXXXX
```
and added this into `.env` of my project which looked like following
```
PWA_PACKAGE_NAME=app.vercel.react_pwa_starter.twa
PWA_SHA256_FINGERPRINTS=SHA-256-From-App-Signing,SHA-256-From-android.keystore
```
I also added them in Vercel's environment variables, this is so that they values stays secret.

With this, I made change change to my script ([git commit](https://github.com/hhimanshu/react-pwa-starter/pull/9/commits/b8c345d99fdf74d51437b70b39b470b09687b4c8)).
With all 3 action items, I made changes which were in my control and merged the [pull request](https://github.com/hhimanshu/react-pwa-starter/pull/9)

I am happy to share that my [app](https://react-pwa-starter.vercel.app/) display the [assetlinks.json](https://react-pwa-starter.vercel.app/.well-known/assetlinks.json) correctly.
I am also able to install the app on my device using `bubblewrap install` command and **no longer see** Custom Chrome tab based on my local `android.keystore` value (still need to double check on Play store app to make sure I did not cause any regression ;-))

But so far, I have been able to see the desired results.

## Next steps?
- [ ] Uninstall installed app (from local build), install from Play Store and make sure app works correctly without Custom Chrome Tab
- [ ] Wait to hear from Google Play team to confirm that the upload keys are updated. Once this happens, I will upload a newer version of `apk` to make sure that this workflow works correctly. This is ensure that @andreban's comment regarding updating app from time to time is indeed supported. 

THANK YOU, once again @joycetoh8  and @andreban for all your help in this matter!

I will report soon on the remaining action items, and will follow up by closing this issue (it's on me!)

**Comment by hhimanshu** [comment]
## Update on Next Step
-[x] Uninstall installed app (from local build), install from Play Store and make sure app works correctly without Custom Chrome Tab

I made mistake in copying the environment variables, which broke production app (from Play store). After I fixed and redeployed app again, I can confirm that both, app from local machine, and Play store are working as expected without Custom Chrome Tab 🔥 🔥

**Comment by andreban** [comment]
Great to hear this! Also, do share the link to Play with us! I'd love to get the app a spin.

**Comment by hhimanshu** [comment]
## Update on Next Step
- [ ] Wait to hear from Google Play team to confirm that the upload keys are updated. Once this happens, I will upload a newer version of apk to make sure that this workflow works correctly. This is ensure that @andreban's comment regarding updating app from time to time is indeed supported.

I received an email last night with the following text

```text
Hello,
We received a request to reset your upload key for React PWA Starter (app.vercel.react_pwa_starter.twa). The new upload key will become valid on Jul 23, 2021 at 3:18 AM GMT. Until the new upload key becomes valid, you can't upload any new APKs.

New upload certificate fingerprints:
MD5:  AB:3C:A2:41:7A:17:89:XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
SHA1: 00:0D:A1:40:52:D8:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

If you didn't request a reset, let us know.

Sincerely,
The Google Play team
```

<img width="742" alt="Screen Shot 2021-07-21 at 7 15 18 AM" src="https://user-images.githubusercontent.com/6589036/126504093-d2ce1a50-02ad-4def-b0ea-348476138a0a.png">

I will update here once I have tested the complete workflow after key update 🕚 
Thanks

**Comment by hhimanshu** [comment]
Happy Friday @joycetoh8 and @andreban. It's update day today since they keys were supposed to be updated.
So, I tried today and happy to confirm that I was able to submit the updated version of app with new `android.keystore` that I submitted to be updated.
I created a video for that to give complete visibility into the process

https://user-images.githubusercontent.com/6589036/126809041-2dfcc2e2-3f7f-49a4-8cfb-b32f1ffc51fe.mp4

Surprisingly, I realized that the update got approved in less than 30 minutes (maybe even lesser). Here is the demo after the app was updated


https://user-images.githubusercontent.com/6589036/126809295-f65a3a80-a256-449a-848c-c584d6cc175a.mp4


I want to THANK YOU both for all the help.
I will publish the app soon to production and share the link with you to try out.

Also, I want to share some details on what my next steps with this project are and I am happy to get your ideas/feedback in

### Next steps
- [ ] Modify this project so that any developer can kick off their PWA project using `npx create-pwa-app <app_name>`. The goal is to give all the necessary tooling and documentation for creating a PWA and distribute via web (Add to Home Screen) and Google Play Store
- [ ] Create detailed documentation of the entire process with process and reasoning, so that developers can learn and understand the details
- [ ] Create more apps based on this starter code demonstrating other use cases such supporting different workbox strategies, for example. The intention is to educate developers what's possible today with PWAs by showing them project artifact and access to GitHub source code.

I know these are big goals and less time (always), but this is the road I am headed to. I would love to take your help in form of feedback and reviews if you have little time bandwidth from time to time

Again, Happy Friday and THANK YOU over and over again!

**Comment by hhimanshu** [comment]
Alright, I have been waiting for this moment. I published the app to Production environment using the steps below

https://user-images.githubusercontent.com/6589036/126823777-63398c1f-1529-4588-99bc-077489d5c988.mp4

And I am happy to announce the the **app is now live** 🥳 🎉 

https://user-images.githubusercontent.com/6589036/126823845-65375ac5-b017-48a6-9886-2e7f0b1035a2.mp4

@andreban, the link to the app is https://play.google.com/store/apps/details?id=app.vercel.react_pwa_starter.twa
@joycetoh8, you may also want to give it a spin, I wouldn't have reached here without your help as well

If you have any feedback or ideas, please let me know and I will follow up.
THANK YOU!
